package main

import (
	"os"
	"strings"
	"fmt"
)

func main() {
	os.Setenv("FOO", "1")
	fmt.Println("FOO:", os.Getenv("FOO"))
	fmt.Println("BAR:", os.Getenv("BAR"))
	os.Unsetenv("FOO")
	fmt.Println()

	for _, e := range os.Environ() {
		pair := strings.Split(e, "=")
		fmt.Printf(pair[0])
	}

}

/*

$ go run Basic/environment-variables.go
FOO: 1
BAR:

ACLOCAL_PATHALLUSERSPROFILEANDROID_HOMEAPPDATACLASSPATHCOMMONPROGRAMFILESCOMPUTERNAMECOMSPECCONFIG_SITECommonProgramFiles(x86)CommonProgramW6432DISPLAYEXEPATHGIT_HOMEGIT_LFS_PATHGOARCHGOBINGOOSGOPATHGOROOTGradleHOMEHOMEDRIVEHOMEPATHHOSTNAMEINFOPATHJAVA_HOMELANGLOCALAPPDATALOGONSERVERMANPATHMEmuHyperv_PathMEmu_PathMINGW_CHOSTMINGW_PACKAGE_PREFIXMINGW_PREFIXMOZ_PLUGIN_PATHMSYSTEMMSYSTEM_CARCHMSYSTEM_CHOSTMSYSTEM_PREFIXMYSQL_HOMENPM_HOMENUMBER_OF_PROCESSORSNVM_HOMENVM_SYMLINKORIGINAL_PATHORIGINAL_TEMPORIGINAL_TMPOSOneDrivePATHPATHEXTPKG_CONFIG_PATHPLINK_PROTOCOLPRINTERPROCESSOR_ARCHITECTUREPROCESSOR_IDENTIFIERPROCESSOR_LEVELPROCESSOR_REVISIONPROGRAMFILESPS1PSModulePathPUBLICPWDProgramDataProgramFiles(x86)ProgramW6432SHELLSHLVLSSH_ASKPASSSYSTEMDRIVESYSTEMROOTTEMPTERMTMPTMPDIRUSERDOMAINUSERDOMAIN_ROAMINGPROFILEUSERNAMEUSERPROFILEVS110COMNTOOLSVS120COMNTOOLSVS140COMNTOOLSWINDIR_asl.log

*/